version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acme_widget_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null # Keep container running
